Update java-microprofile devfile to add support of bootable jar and EAP XP 2.0
redhat-developer/codeready-workspaces pull request #401
Opened 2021-01-13 10:34 UTC by svor

### What does this PR do?

- Updates an image for dev-container to registry.redhat.io/jboss-eap-7/eap-xp2-openjdk11-openshift-rhel8:2.0-3
- Updates sample to use bootable jar feature
- Adds commands to demonstrate bootable jar feature

![screenshot-codeready-orfo apps ci-ln-isi0dq2-f76d1 origin-ci-int-gce dev openshift com-2021 01 13-12_00_56](https://user-images.githubusercontent.com/1271546/104437263-399dd600-5597-11eb-8fd3-70dd7e707645.png)

_Note: For some reason if WildFly server was started in bootable-jar mode via the command from workspace view it will stop immediately after the command is completed but if run the same command line in the dev-terminal, the server will continue running. That's why sleep command was added into 2.3 Botable jar. Build and run in debug command_

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1419

#### Release Notes

#### Docs PR (if applicable)

2021-01-13 10:43 UTC, svor commented
@ehsavoie it's updated version with bootable-jar support, pls take a look

2021-01-13 17:26 UTC, nickboldt commented
Do we know if there's a matching 2.0-3 version for openj9? 

I don't see one out yet...

```
FATA[0003] Error parsing image name "docker://registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8": Error reading manifest latest in registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8: unknown: Not Found 
```

So... we need to accomodate this toggle script:

https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.6-rhel-8/dependencies/che-devfile-registry/build/scripts/swap_images.sh#L18

Either we need to REMOVE XP2 from Z and P devfile registry, or point at a different image. 

If removing, see empty files added with this commit https://github.com/redhat-developer/codeready-workspaces/commit/4c64fb55a7257db8d39e7f9f3efdda2fd9e4aa7f to remove the Fuse devfile on Z & P.

If pointing at a different image... then maybe we want to fall back to the XP1 image, for only Z & P (using the same empty file logic to disable the XP1 devfile for amd64) ? 

WDYT @svor @ericwill @aghatwal @kcrane ?

2021-01-13 17:32 UTC, ericwill commented
> Do we know if there's a matching 2.0-3 version for openj9?
> 
> I don't see one out yet...
> 
> ```
> FATA[0003] Error parsing image name "docker://registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8": Error reading manifest latest in registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8: unknown: Not Found 
> ```
> 
> So... we need to accomodate this toggle script:
> 
> https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.6-rhel-8/dependencies/che-devfile-registry/build/scripts/swap_images.sh#L18
> 
> Either we need to REMOVE XP2 from Z and P devfile registry, or point at a different image.
> 
> If removing, see empty files added with this commit [4c64fb5](https://github.com/redhat-developer/codeready-workspaces/commit/4c64fb55a7257db8d39e7f9f3efdda2fd9e4aa7f) to remove the Fuse devfile on Z & P.
> 
> If pointing at a different image... then maybe we want to fall back to the XP1 image, for only Z & P (using the same empty file logic to disable the XP1 devfile for amd64) ?
> 
> WDYT @svor @ericwill @aghatwal @kcrane ?

@ehsavoie do you know if there will be XP2 image for Z and P architectures?

I suppose the quickest way around this is to remove the image from Z and P, but I'm not sure if that's acceptable (it would mean a regression in the number of stacks available on Z and P). If time permits, we should probably point to the XP1 file, if there is no XP2 image for architectures by the end of the week.

2021-01-13 18:14 UTC, nickboldt requested changes
Marking 'changes needed' to prevent accidentally merging this w/o a Z+P solution

2021-01-14 14:07 UTC, svor commented
@ericwill @nickboldt to keep having this devfile on Z and P we can use old image ( registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3) for this devfile as well. I've just tested it and everything works. Do you have any concerns to use old `registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3` image in this devfile?

2021-01-14 14:12 UTC, ericwill commented
> @ericwill @nickboldt to keep having this devfile on Z and P we can use old image ( registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3) for this devfile as well. I've just tested it and everything works. Do you have any concerns to use old `registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3` image in this devfile?

I think it should be okay, we'll just have to document it as a known issue. @nickboldt WDYT?

2021-01-14 20:02 UTC, nickboldt commented
"everything works" 

> except the new bootable jar feature?

2021-01-15 08:05 UTC, svor commented
@nickboldt bootable jar feature works with old image as well

2021-01-15 14:13 UTC, nickboldt commented
wow, ok, so I wonder why we needed a new image and what all the fuss was about waiting for XP 2, if bootable jar works w/ XP 1. 

*SO CONFUSED*

2021-01-15 14:41 UTC, ehsavoie commented
bootable jar is **not supported** with XP1

2021-01-15 14:52 UTC, svor commented
but bootable-jar plugin will download XP2 artifacts and it doesn't matter where it will be executed in registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3 or in registry.redhat.io/jboss-eap-7/eap-xp2-openjdk11-openshift-rhel8:2.0-3

2021-01-15 15:00 UTC, svor commented
OK, probably it makes sense to have 2 devfiles with microprofile:
- the first one which we have now: to run WildFly server inside the container and for this we continue using old XP1 image `registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3`
- the second one is for bootbale jar (with same sample but another version) and the image for dev-container will be `registry.redhat.io/codeready-workspaces/plugin-java11-rhel8`

2021-01-15 15:01 UTC, svor commented
@nickboldt is this way good for you?

2021-01-15 17:28 UTC, ehsavoie commented
@svor it's my turn to get confused :) this is XP1 registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3 which is out of date in terms of MP version and EAP too. You need to provide one image with XP2 builder image:
 *registry.redhat.io/jboss-eap-7/eap-xp2-openjdk11-openshift-rhel8
and one with registry.redhat.io/codeready-workspaces/plugin-java11-rhel8 (or registry.access.redhat.com/ubi8/openjdk-11) for bootable jar.

2021-01-15 17:52 UTC, svor commented
> @svor it's my turn to get confused :) this is XP1 registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3 which is out of date in terms of MP version and EAP too. You need to provide one image with XP2 builder image:
> *registry.redhat.io/jboss-eap-7/eap-xp2-openjdk11-openshift-rhel8

Yep, but there is no a matching 2.0-3 version for openj9 which is needed for Z & P. 
So, we have to decide: if we go with `registry.redhat.io/jboss-eap-7/eap-xp2-openjdk11-openshift-rhel8` and don't include the devfile for Z & P which is regression or we proceed with `registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3`

2021-01-15 19:06 UTC, svor commented
@nickboldt @ericwill @ehsavoie the PR was updated. 
I've added a new devfile with name **00_java-microprofile-bootable**. As an image for dev-container it uses `registry.redhat.io/codeready-workspaces/plugin-java11-rhel8:2.6` and contains commands to play with bootable jar feature.

Another **jboss-eap-quickstart** devfile (the old one) is still without changes, we can replace `registry.redhat.io/jboss-eap-7/eap-xp1-openjdk11-openshift-rhel8:1.0-3` image with the latest XP2 in another PR when corresponding openj9 image will be published.

2021-01-15 20:00 UTC, nickboldt commented
if bootable is meant to run on simple java11 image registry.redhat.io/codeready-workspaces/plugin-java11-rhel8:2.6, and XP1/2 is meant to run on XP1/2 image, then this is fine.

However, we could also have:

* devfile for bootable, all arches (either openjdk11 or openj9-11)
* devfile for XP2 for amd64 (because 2.0 is only available for amd64 right now)
* devfile for XP1 for Z&P (so there's something for the Z&P people too, which we can update to 2.0 in CRW 2.7)

To achieve this, we only need 2 named devfiles, but the Z&P versions can in fact be different from the amd64 one. We achieve like we did for Fuse, with s390x and ppc64le variants in the same folder:

https://github.com/redhat-developer/codeready-workspaces/tree/crw-2.6-rhel-8/dependencies/che-devfile-registry/devfiles/02_java-jboss-fuse

(The devfile can be empty if no support exists for that arch, or simply a different file, if the supported commands/features are different.)

2021-01-18 09:00 UTC, ehsavoie commented on dependencies/che-devfile-registry/devfiles/00_java-microprofile-bootable/devfile.yaml
> +    name: 4. Hot update
This 'action' will only work with the Build and run in debug. Should we duplicate "Build and run in debug" to an action that will not start with the debug parameters ?

2021-01-18 09:59 UTC, svor commented on dependencies/che-devfile-registry/devfiles/00_java-microprofile-bootable/devfile.yaml
> +    name: 4. Hot update
as for me it's better to stay in current state, because in another way the user will need to run `5. Stop server` after `3. Build and run in debug` if he wants to do `4. Hot update`  (it brakes the order)

2021-01-19 16:49 UTC, merged

2021-01-19 16:52 UTC, nickboldt commented
I've merged this, but @ehsavoie if you have followup concerns/improvements please submit a PR.

I also find it interesting that the bootable jar devfile uses the CRW java11+maven3.6 sidecar, whereas the XP1 devfile uses the XP1 sidecar. Is that correct? we have no devfile that uses XP2 image at this point...

2021-01-19 18:47 UTC, ehsavoie commented
@nickboldt The XP2 devfiles with images should be the 'same' as XP1 with the upgrade in terms of name. The Z & P should have been released today (afaik).

2021-01-19 20:16 UTC, nickboldt commented
Still no openj9 XP2 image:
```
$➔ skopeo inspect docker://registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8
FATA[0001] Error parsing image name "docker://registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8": Error reading manifest latest in registry.redhat.io/jboss-eap-7/eap-xp2-openj9-11-openshift-rhel8: unknown: Not Found 
```

Only EAP XP for J9 is https://catalog.redhat.com/software/containers/jboss-eap-7/eap-xp1-openj9-11-openshift-rhel8/5eecf6ef46bc301a95a1e99b -- no XP2 yet.

@ehsavoie if you want us to update the XP1 devfile to XP2 container image (for X only, keeping XP1 for Z&P) we can do that easily.