Update devfile-registry templates
redhat-developer/codeready-workspaces pull request #425
Opened 2021-02-16 15:07 UTC by tolusha

Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
* Upstream OpenShift template is adopted.
* Added `build/scripts/sync_template.sh` to sync templates

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/RHDEVDOCS-2483

2021-02-16 15:35 UTC, nickboldt commented on dependencies/che-devfile-registry/build.sh
> +# Copyright (c) 2019-2020 Red Hat, Inc.
Why change the dates??

2021-02-16 15:35 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
> +# Copyright (c) 2018-2020 Red Hat, Inc.
looks like upstream has invalid date range

2021-02-16 15:36 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile
> +FROM registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-114 AS registry
you're going backwards here. Please update upstream to latest.

2021-02-16 15:36 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile
> +# FROM registry.redhat.io/rhel8/httpd-24:1-92 AS registry
you're going backwards here. Please update upstream to latest.

2021-02-16 15:36 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile
> +RUN yum update -y systemd && yum clean all && rm -rf /var/cache/yum && \
why only systemd? why not full update??

2021-02-16 15:36 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.entrypoint.sh
> -  chown -R ${USER_NAME:-jboss}:${USER_NAME:-jboss} /var/www/html
why remove this?

2021-02-16 15:37 UTC, nickboldt commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.install.sh
> +microdnf --disablerepo=fedora30-updates --disablerepo=fedora30-secondary-updates install -y findutils bash wget yum gzip tar python3-six python3-pip && microdnf -y clean all
cannot use fedora30 repo in Brew. Brew = RHEL, Fedora = upstream. Hard no here, will fail in Brew.

2021-02-16 15:38 UTC, nickboldt commented on dependencies/che-devfile-registry/build/scripts/list_referenced_images.sh
> +readarray -d '' devfiles < <(find "$1" -name 'devfile.yaml' -print0)
this checks all the devfile.yaml files... so why is line 10 being changed to "meta.yaml" ??

2021-02-16 15:39 UTC, nickboldt commented on dependencies/che-devfile-registry/build/scripts/sync_template.sh
> +# Copyright (c) 2019-2020 Red Hat, Inc.
new file, old copyright date.

2021-02-16 15:40 UTC, nickboldt commented on dependencies/che-devfile-registry/build/scripts/write_image_digests.sh
> -  local yaml_file="$1"
you have removed a bunch of code that is needed in downstream. Please talk to @kcrane and @ghatwala about this.

2021-02-16 15:41 UTC, nickboldt commented on dependencies/che-devfile-registry/build/scripts/write_image_digests.sh
> +readarray -d '' devfiles < <(find "$1" -name 'devfile.yaml' -print0)
why not use list_referenced_images.sh ?

2021-02-16 15:42 UTC, nickboldt commented on dependencies/che-devfile-registry/build/scripts/write_image_digests.sh
> +    handle_error "$image"
I'm not sure we want to allow the case where digest couldn't be found, and just include a tag instead. Acceptable in upstream, NOT acceptable in product.

2021-02-16 15:43 UTC, nickboldt commented on dependencies/che-devfile-registry/deploy/openshift/che-devfile-registry.yaml
> +     CODEREADY_DEVFILE_IMAGES_REGISTRY_URL: ${CODEREADY_DEVFILE_IMAGES_REGISTRY_URL}
do we have to use "CODEREADY_*" in variables? Codeready is a brand, with 5+ products under it (Studio, Workspaces, Builder, Containers, etc.) Could we use CRW_ or Workspaces_ here?

2021-02-16 15:44 UTC, nickboldt commented on dependencies/che-devfile-registry/deploy/openshift/che-devfile-registry.yaml
> +  description: CodeReady Workspaces devfile registry version which defaults to nightly
today there is no nightly default tag in registry.redhat.io. Are you also defaulting to quay.io/crw/ for your nightly tags? Because that's the only place they'll ever exist :D

2021-02-16 18:35 UTC, ericwill requested changes

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/README.md
> +# Eclipse Che devfile registry
This should be `CodeReady Workspaces devfile registry`, like before

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/README.md
> +[![Master Build Status](https://ci.centos.org/buildStatus/icon?subject=master&job=devtools-che-devfile-registry-build-master/)](https://ci.centos.org/job/devtools-che-devfile-registry-build-master/)
All these centos-ci links can be removed, we are not using centos-ci anymore.

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/README.md
> -### Build in Brew
The brew stuff needs to stay, but the upstream changes can also be added as they are relevant

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/arbitrary-users-patch/build_images.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright year needs to stay `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/arbitrary-users-patch/entrypoint.sh
> +# Copyright (c) 2019-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/arbitrary-users-patch/happy-path/build_happy_path_image.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/dockerfiles/Dockerfile
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Upstream dates need to be fixed but they cannot be reintroduced here, either

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/dockerfiles/entrypoint.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.Dockerfile
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.cache_projects.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/dockerfiles/rhel.entrypoint.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/scripts/check_mandatory_fields.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/scripts/index.sh
> +# Copyright (c) 2018-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/scripts/list_containers.sh
> +# Copyright (c) 2019-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:35 UTC, ericwill commented on dependencies/che-devfile-registry/build/scripts/list_referenced_images.sh
> +# Copyright (c) 2019-2020 Red Hat, Inc.
Copyright needs to be `2021`

2021-02-16 18:50 UTC, ericwill commented
@tolusha if you like, you can just contribute the templates in this PR, since it's not fair for you to have to do devfile registry syncing. I will open a follow-up PR to sync the upstream devfile registry to this one.

2021-02-16 18:52 UTC, nickboldt commented on dependencies/che-devfile-registry/README.md
> +[![Master Build Status](https://ci.centos.org/buildStatus/icon?subject=master&job=devtools-che-devfile-registry-build-master/)](https://ci.centos.org/job/devtools-che-devfile-registry-build-master/)
yeah, we never used CI Centos for CRW, so they were never meant to be synced to downstream

2021-02-17 12:45 UTC, tolusha commented
@ericwill 
Make sense. I will open a new PR specifically for OpenShift templates. 
Besides devfile registry syncing it is needed to sync plugin registry as well.

2021-02-17 12:45 UTC, closed without merging