To support CRW-1637
redhat-developer/codeready-workspaces pull request #455
Opened 2021-03-22 11:23 UTC by ghatwala

To support CRW-1637
    1. Removed hardcoded memoryLimit values from all CRW devfiles( 18 out of 19 devfiles affected )
    2. Most the values to plugin's yamls.
    3. Most of scenarios all plugins's had similar or higher memoryLimit as compared with devfiles value in them except below
       - dependencies/che-plugin-registry/v3/plugins/ms-vscode/node-debug2/1.42.3/meta.yaml ('512Mi' to '1Gi')
       - dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml ('512Mi' to '1024Mi')
       - dependencies/che-plugin-registry/v3/plugins/redhat/php-debugger/1.13.0/meta.yaml (added "memoryLimit: 512Mi")
    4. JIRA link - https://issues.redhat.com/browse/CRW-1637

Signed-off by : Amit Ghatwal <ghatwala@us.ibm.com>

2021-03-22 12:57 UTC, svor requested changes
Hello! It's wrong to remove `memoryLimit` attribute from the component with type `dockerimage`. I think you need to refactor only `chePlugin` components

2021-03-22 12:58 UTC, svor commented on dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
> -    memoryLimit: 1024Mi
I think it's wrong to remove `memoryLimit` from dev-container

2021-03-23 12:17 UTC, ghatwala commented on dependencies/che-devfile-registry/devfiles/00_java-eap-maven/devfile.yaml
> -    memoryLimit: 1024Mi
can you please review @svor again now if refactoring complies?

2021-03-23 13:01 UTC, svor requested changes

2021-03-23 13:01 UTC, svor commented on dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml
> +      memoryLimit: "1024Mi"
1Gi looks better to me

2021-03-26 05:38 UTC, ghatwala commented on dependencies/che-plugin-registry/v3/plugins/redhat/dependency-analytics/0.1.0/meta.yaml
> +      memoryLimit: "1024Mi"
Updated as 1Gi.

2021-03-26 05:39 UTC, ghatwala commented on dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/devfile.yaml
> -    memoryLimit: 512Mi
Done , moved this memory limit under  type `dockerimage`

2021-03-26 05:39 UTC, ghatwala commented on dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/devfile.yaml
> -    memoryLimit: 1Gi
Done , moved this memory limit under  type `dockerimage`

2021-03-26 05:39 UTC, ghatwala commented on dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/devfile.yaml
> -    memoryLimit: 768Mi
Done , moved this memory limit under  type `dockerimage`

2021-03-26 08:01 UTC, svor reviewed
@ghatwala Your changes are OK to me, just one more remark: 
Since you've increased `memoryLimit` for `node-debug2` plugin, you need to update `globalMemoryLimit` for devfiles where this plugin is used. Take a look at these files and increase the value by 512:
- 03_web-nodejs-simple devfile: https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/03_web-nodejs-simple/meta.yaml#L6
- 04_nodejs-configmap https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml#L6
- 04_nodejs-mongo https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/04_nodejs-mongo/meta.yaml#L6

The same you need to do for devfiles which use dependency-analytics (+512):
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/00_java-eap-maven/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/00_java-microprofile-bootable/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/00_java-microprofile-xp2/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/02_java-fuse/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/02_java-maven/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/03_spring-boot-http-booster/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/03_vertx-http-booster/meta.yaml#L6

And for devfiles with php-debugger (+256):
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/05_php-cake/meta.yaml#L6
- https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/devfiles/05_php-web-simple/meta.yaml#L6

2021-03-26 10:37 UTC, ghatwala commented
Updated `globalMemoryLimit` for devfiles as required - @svor

2021-03-26 11:30 UTC, svor approved these changes
LGTM

2021-03-26 13:24 UTC, nickboldt commented on dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml
> +globalMemoryLimit: 3816Mi
if you removed 512M from typescript, and 1280M from openshift connector, should this value be larger?

2021-03-26 13:25 UTC, nickboldt commented on dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml
> -    memoryLimit: 512Mi
does the dotnet meta.yaml need an increased globalMemoryLimit too?

2021-03-26 14:01 UTC, svor commented on dependencies/che-devfile-registry/devfiles/05_dotnet/devfile.yaml
> -    memoryLimit: 512Mi
no, this plugin is still included in the workspace and the value of total memory limit is still the same

2021-03-30 12:54 UTC, ghatwala commented on dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml
> +globalMemoryLimit: 3816Mi
@svor - anything on above , is this needed ?

2021-03-30 13:19 UTC, svor commented on dependencies/che-devfile-registry/devfiles/04_nodejs-configmap/meta.yaml
> +globalMemoryLimit: 3816Mi
@nickboldt @ghatwala we remove 512M only from devfile's description but the workspace still uses this 512M which is declared in plugin's meta.yaml. 
This value should be larger because after current changes node-debug2 [uses 1Gi instead of 512Mi](https://github.com/redhat-developer/codeready-workspaces/pull/455/files#diff-e132e318ddaf52b6ecccccd3ce5631cfad00c3dc8fdd82016edb9b1124b903e4R17) and `globalMemoryLimit` should include this value .

2021-03-30 14:12 UTC, merged

2021-03-30 14:13 UTC, nickboldt commented
cherrypicked to 2.8 branch too