chore(plugin-registry-generator): adding new option to be used in dev mode to use public images instead of unreleased crw images
redhat-developer/codeready-workspaces pull request #509
Opened 2021-06-04 08:41 UTC by sunix

### What does this PR do?

### What issues does this PR fix or reference?

#### Release Notes

#### Docs PR (if applicable)

2021-06-04 09:15 UTC, benoitf commented on dependencies/che-plugin-registry/tools/build/src/build.ts
> +    if (this.useDevImages) {
I would find a different way as the idea is to have like 100% code being upstream (and then even use the che-plugin-registry tool itself)

so probably we could have upstream a 'regexp/sed/replace' settings to apply on images

and in downstream we would only provide the parameter.

Else by merging this PR, codebase will differ

2021-06-04 09:57 UTC, sunix commented on dependencies/che-plugin-registry/tools/build/src/build.ts
> +    if (this.useDevImages) {
yep i was thinking backporting upstream.

2021-06-04 12:04 UTC, nickboldt commented
8 files changed and 100s of lines of code when a single line of sed would have achieved the same thing. +0 for this, especially this close to CRW 2.9 GA freeze. 

I'd be happier with this for 2.10

2021-06-04 12:08 UTC, nickboldt commented
Another approach would be to pass a flag to https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/build/scripts/find_image_alternate_urls.sh so that instead of using internal brew images, we use external quay images.

Then you would be able to use the existing transformation code/logic already in the dockerfile to handle the case where we need to fetch digests for unreleased images.

2021-06-08 07:27 UTC, sunix commented
@nickboldt I don't think the last proposal is the right approach:
- It is not documented: we don't know the context, anyone coming from outside won't know how and when these script should be used
- It's fragile, no unit tests, if i pass a different parameter, i have no guarantees that these will work.
- So I read your flow many times but i found this not safier and equally complex compared to this PR
- Size is not that big if you ignore the tests folder.

2021-06-09 01:05 UTC, nickboldt requested changes
Eric and Florent have both requested this change be done upstream first. You also have 4 failing tests. 

Therefore, -1.

2021-06-28 18:47 UTC, nickboldt commented
three weeks w/o an update. Closing - feel free to reopen if there's more work happening here in downstream (or link to your changes upstream? )

2021-06-28 18:47 UTC, closed without merging