feat(plugin-registry): Update the Openshift...
redhat-developer/codeready-workspaces pull request #542
Opened 2021-07-05 14:39 UTC by nickboldt

### What does this PR do?

feat(plugin-registry): Update the Openshift connector plugin to latest

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2021-07-05 14:40 UTC, nickboldt commented
replacement for https://github.com/redhat-developer/codeready-workspaces/pull/530 so that the build test will pass (missing secrets when run from developer fork's topic branch)

2021-07-06 07:08 UTC, svor approved these changes

2021-07-06 16:53 UTC, ericwill requested changes
Needs to have dependencies updated first, and we should wait until the vscode-commons dependency has been removed

2021-10-11 12:37 UTC, vinokurig commented on dependencies/che-plugin-registry/che-theia-plugins.yaml
> +    extension: https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/v31f30bd/vscode-openshift-connector-v0.2.7.vsix
```suggestion
    extension: https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/v1cb50f5/vscode-openshift-connector-v0.2.9.vsix
```

2021-10-18 13:36 UTC, mohitsuman commented
There will be a new release of the OpenShift Connector `0.2.10` tomorrow. We need to update the PR accordingly. The fix around latest oc will also be included.

2021-10-20 22:02 UTC, mohitsuman commented
New release of OpenShift Connector 0.2.10 is now released. Here are the artifacts: https://github.com/redhat-developer/vscode-openshift-tools/releases/tag/v0.2.10

2021-11-04 15:03 UTC, svor commented on dependencies/che-plugin-registry/che-theia-plugins.yaml
> +    extension: https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/v1cb50f5/vscode-openshift-connector-v0.2.9.vsix
```suggestion
    extension: https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/download/va21efef/vscode-openshift-connector-v0.2.11.vsix
```

2021-11-04 15:03 UTC, svor commented on dependencies/che-plugin-registry/che-theia-plugins.yaml
> +      revision: v0.2.9
```suggestion
      revision: v0.2.11
```

2021-11-04 18:00 UTC, merged

2021-11-04 19:02 UTC, nickboldt commented
backported to 2.13 as 57c110e7