fix: consume generator tool from upstream as an npm package
redhat-developer/codeready-workspaces pull request #564
Opened 2021-08-06 12:52 UTC by vinokurig

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
Consume generator tool from upstream as an npm package

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1928

#### Release Notes

#### Docs PR (if applicable)

2021-08-06 13:05 UTC, svor approved these changes

2021-08-06 15:24 UTC, ericwill reviewed
This is for 2.11 right? Shouldn't this PR be against the `crw-2.11-rhel8` branch then?

2021-08-06 15:24 UTC, ericwill commented on dependencies/che-plugin-registry/build.sh
> +npx @eclipse-che/plugin-registry-generator@7.35.0-dev-01ff6be --root-folder:"$(pwd)" --output-folder:"$(pwd)/output" "${BUILD_FLAGS_ARRAY[@]}"
If 2.11 is based on Che 7.34 we shouldn't be using upstream bits from Che 7.35. If necessary, let's backport upstream changes to `7.34.x` branch and publish the npm library from that. We can then consume that 7.34 version here.

2021-08-06 15:34 UTC, nickboldt commented on dependencies/che-plugin-registry/build.sh
> +npx @eclipse-che/plugin-registry-generator@7.35.0-dev-01ff6be --root-folder:"$(pwd)" --output-folder:"$(pwd)/output" "${BUILD_FLAGS_ARRAY[@]}"
This PR is for crw-2-rhel-8 = 2.12, so as it stands I'm OK with it. We'll need a new Prod Sec exception to be noted about this change, however, as it's a new npm dependency that we build (but which is hosted by 3rd party).

2021-08-06 15:43 UTC, nickboldt approved these changes
This PR is for crw-2-rhel-8 = 2.12, so as it stands I'm OK with it... though the JIRA says fixversion = 2.11, so we'll need a second PR for the 2.11 branch.

I also don't love that there are only "-dev-" versions in https://www.npmjs.com/package/@eclipse-che/plugin-registry-generator for the 2.11 release, I'd prefer to see a stable release at npmjs. Can we do some 7.yy.z releases in addition to the nightly devs?

We'll need a new Prod Sec exception to be noted about this change, however, as it's a new npm dependency that we build (but which is hosted by 3rd party). https://docs.google.com/document/d/1nw_O1QeG5bg1jfpoSkmABNiCjLpxxc9bSQXXLo8jgJw/edit#heading=h.ttxuwnu2u1jf

How will we ensure we're using the latest correct version of the package in 2.x and 2.11 branches? 

Can we add this version dependency into https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/VERSION.json and add some build process that pulls the version from there to make sure we build with the correct version?

2021-08-10 14:27 UTC, vinokurig commented on dependencies/che-plugin-registry/build.sh
> +npx @eclipse-che/plugin-registry-generator@7.35.0-dev-01ff6be --root-folder:"$(pwd)" --output-folder:"$(pwd)/output" "${BUILD_FLAGS_ARRAY[@]}"
Opened another PR for the `2.11` branch https://github.com/redhat-developer/codeready-workspaces/pull/566

2021-08-10 15:11 UTC, nickboldt commented on dependencies/che-plugin-registry/build.sh
> +npx @eclipse-che/plugin-registry-generator@7.35.0-dev-01ff6be --root-folder:"$(pwd)" --output-folder:"$(pwd)/output" "${BUILD_FLAGS_ARRAY[@]}"
thx, looks good over in the other PR, except for the question about which z version to use...

2021-08-10 20:06 UTC, nickboldt requested changes
Can you collect the version of the generator from a centalized place, eg.,

```
 ECPRG_VER=$(curl -sSLo- https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2-rhel-8/dependencies/VERSION.json \
| yq -r '.Other["@eclipse-che/plugin-registry-generator"]["2.12"]'); echo $ECPRG_VER
```

2021-08-11 07:52 UTC, vinokurig commented
@nickboldt 
> Can you collect the version of the generator from a centalized place, eg.,
>
>```
>ECPRG_VER=$(curl -sSLo- https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2-rhel->8/dependencies/VERSION.json \
>| yq -r '.Other["@eclipse-che/plugin-registry-generator"]["2.12"]'); echo $ECPRG_VER
>```

Done.

2021-08-11 08:57 UTC, svor commented
> ECPRG_VER=$(curl -sSLo- https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2-rhel-8/dependencies/VERSION.json \
| yq -r '.Other["@eclipse-che/plugin-registry-generator"]["2.12"]'); echo $ECPRG_VER

@nickboldt I don't think it is good to have hardcoded version in the script. But if we do that, shouldn't we use `2.x` for `crw-2-rhel-8` branch?

And it would be better to move that value into the varible in the script.

2021-08-11 14:40 UTC, nickboldt commented
> hardcoded version in the script. 

Agreed, better to pull the version from https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/VERSION.json#L2 

That way it'll automatically be updated to 2.13 when we move into the 2.12 branch and update 2.x to a newer future version

2021-08-11 21:44 UTC, nickboldt commented
ready to merge in both 2.11 and 2.x branches (change is now the same in both places and can simply compute its version and associated generator version, as long as the VERSION.json file in each branch is kept up to date.

2021-08-11 21:44 UTC, nickboldt approved these changes

2021-08-11 21:49 UTC, nickboldt commented
related: https://github.com/eclipse-che/che-plugin-registry/pull/1027

2021-08-12 08:11 UTC, svor approved these changes

2021-08-12 15:02 UTC, benoitf approved these changes

2021-08-12 15:05 UTC, merged

2021-08-13 02:52 UTC, nickboldt commented
Failed -- need to copy VERSION.json from upstream to midstream and move it into the root. 

https://github.com/redhat-developer/codeready-workspaces-images/commit/947db4159ac097ca45788d88b06493abb2edb3ee

Respinning: 
* https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-pluginregistry_2.11/11/
* https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-pluginregistry_2.x/204/

2021-08-13 16:56 UTC, nickboldt commented
Had to do a few more things for this to work, including moving to 0.0.2 version of che-openshift-auth plugin (as the 0.0.1 no longer exists). https://github.com/eclipse-che/che-plugin-registry/pull/1028