Devfile for CRW devfile registry
redhat-developer/codeready-workspaces pull request #578
Opened 2021-08-30 17:07 UTC by sunix

This is a devfile based on the upstream one to build/run/publish(to surge.sh) the crw devfile registry.

### What does this PR do?

### What issues does this PR fix or reference?

#### Release Notes

#### Docs PR (if applicable)

2021-09-07 19:56 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    image: 'quay.io/eclipse/che-devfile-registry:nightly'
why does the CRW devfile registry load the che-devfile-registry:nightly image? Also `:nightly` is dead; use `:next` for Che image tags.

2021-09-07 19:56 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    image: 'quay.io/eclipse/che-plugin-registry-dev:latest'
and here you're using the upstream `:latest` image tag. Again, why not the CRW image?

2021-09-07 19:58 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +        command: REPO_DIR=/projects/codeready-workspaces/dependencies/che-devfile-registry ./build/dev/publish-devfile-registry-to-surge.sh
there is no such script in CRW repo. https://github.com/redhat-developer/codeready-workspaces/tree/crw-2-rhel-8/dependencies/che-devfile-registry/build contains no "dev" folder.

2021-09-07 19:59 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
Using the upstream Che registries while dogfooding CRW means you'll be mixing in unsupported Che content into the CRW repo. Is that wise?

2021-09-07 20:00 UTC, nickboldt requested changes
-1. I don't think this will work since the surge scripts don't exist in CRW repo. I'm also not sure why you're mixing Che stuff into the CRW build.

2021-09-08 08:28 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +    image: 'quay.io/eclipse/che-devfile-registry:nightly'
because it's a copy-paste :) I can rework it to use a CRW image yes

2021-09-08 08:31 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +    image: 'quay.io/eclipse/che-plugin-registry-dev:latest'
do we have `-dev` builder images in CRW ?

2021-09-08 08:31 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +        command: REPO_DIR=/projects/codeready-workspaces/dependencies/che-devfile-registry ./build/dev/publish-devfile-registry-to-surge.sh
no but this is using the one from upstream, this devfile is cloning both project

2021-09-08 08:35 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
These dogfooding devfiles would never be delivered to the customer. It is also supposed to be portable and we should be able to code CRW from a Che cluster.

2021-09-08 11:41 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    image: 'quay.io/eclipse/che-plugin-registry-dev:latest'
Not as far as I know, other than theia-dev. You can see them in RHEC here: 
* https://catalog.redhat.com/software/containers/search?q=codeready-workspaces
or in quay:
* https://quay.io/organization/crw

What is the purpose of -dev containers? We build everything in Brew (or commandline w/ podman).

2021-09-08 11:42 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +        command: REPO_DIR=/projects/codeready-workspaces/dependencies/che-devfile-registry ./build/dev/publish-devfile-registry-to-surge.sh
Since the CRW registry is a fork of the upstream Che registry (different devfiles, different/subset of plugins/sidecars) why are you trying to mix up and downstream into a single dev env?

2021-09-08 11:44 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
> we should be able to code CRW from a Che cluster.
![image](https://user-images.githubusercontent.com/227597/132503316-720b89cc-76f6-4432-baf8-12b545a47a71.png)

Since CRW is a fork, why would you ever start with Che to build CRW? Do you plan to include scripts to transform che registries into crw ones, like we do with operator and chectl/crwctl, stripping out functionality that doesn't exist downstream?

2021-09-10 15:18 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
For the same reason some are using their local dev environment to test/contribute to this https://github.com/redhat-developer/codeready-workspaces.
It's like having a .vscode folder inside a che repo. It is about coding.

2021-09-10 15:22 UTC, sunix commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
CRW is a cloud application like any others ... why can't I use Che to contribute to CRW ? in that case we should forbid people using VSCode, or IntelliJ ...

2021-09-10 15:38 UTC, nickboldt commented on dependencies/che-devfile-registry/devfile.yaml
> +    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
ok, that makese sense. As to `devfiles would never be delivered to the customer` I think we're OK there since they're not included in the devfile registry itself.

2021-12-13 21:38 UTC, nickboldt commented
Tempted to close this unmerged. @sunix will you be providing updates on this PR, or should we close it?

2022-01-25 15:39 UTC, closed without merging

2022-01-25 15:39 UTC, nickboldt commented
Closing as no followup from @sunix :(

2022-01-25 15:49 UTC, sunix commented
I think this one would have been interesting if someone were using che or crw to contribute to the crw devfile registry. But if no one use it, let's skip it.

2022-01-25 15:50 UTC, sunix commented
also it would deserve a devfile2 migration

2022-01-25 17:13 UTC, nickboldt commented
If you want to contrib, happy to have it... as long as it's a complete devfile v2 solution :D