chore: Add GitHub action to publish plugin-registry latest
redhat-developer/codeready-workspaces pull request #674
Opened 2022-01-19 14:59 UTC by vinokurig

Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
Publish the plugin-registry with `latest` version to `surge.sh` and `github-pages`. The action is triggered on each commit to the `crw-2-thel-8` branch. This is needed to generate devfile v2 templates for CRW, see https://issues.redhat.com/browse/CRW-2500.
### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-2644

#### Release Notes

#### Docs PR (if applicable)

2022-01-20 08:52 UTC, svor commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
maybe it makes sense to add some information about plugin-registry into the URL, like:
`https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/dependencies/che-plugin-registry/$VERSION_DIR/v3/plugins/`

WDYT?

2022-01-20 13:06 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
whether you include `dependencies/che-plugin-registry` in the path or not, doesn't really matter.

But what IS mandatory is the arch. Otherwise we have the same registry for BOTH x64 (openjdk) and ppc64le/s390x (openj9). 

Pleae add a path segment for `/$(uname -m)/`

2022-01-20 13:07 UTC, nickboldt commented
Do we need to publish to BOTH surge and github pages? If only one URL is going to be used in builds, why publish 2x?

2022-01-20 13:08 UTC, nickboldt requested changes
needs arch support; unclear why we include BOTH surge and gh pages. Suggest only using gh.

2022-01-20 13:09 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +# Copyright (c) 2020-2022 Red Hat, Inc.
You guys and your backdated copyrights, I tell ya. New file = 2022. Old file = old date - 2022.

2022-01-20 13:09 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +      - crw-2-rhel-8
should we also be publishing for the stable branches, crw-2.*-rhel-8? But those should go to :latest instead of :next.

2022-01-20 13:10 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          docker pull quay.io/crw/pluginregistry-rhel8:latest
if publishing from crw-2-rhel-8 branch (aka 2.x aka main) then use :next, not :latest

2022-01-20 13:11 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          VERSION_DIR="latest"
if publishing from crw-2-rhel-8 (2.x / main) branch, use :next, not :latest.

:latest is reserved for the stable branch, built from crw-2.yy-rhel-8 (currently crw-2.14-rhel-8).

2022-01-21 20:59 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
this is in the original spec in https://issues.redhat.com/browse/CRW-2644:
```
use a URL like https://redhat-developer.github.io/codeready-workspaces/dependencies/che-plugin-registry/[branchOrTag]/[ARCH]/v3/
```

2022-01-24 10:24 UTC, vinokurig commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +      - crw-2-rhel-8
done

2022-01-24 10:57 UTC, vinokurig commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
The URL is now looks like: 
```
https://redhat-developer.github.io/codeready-workspaces/che-plugin-registry/[branch]/[ARCH]/v3/
```
I don't think we need to include the `dependencies` sub folder.

2022-01-24 11:03 UTC, vinokurig commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          docker pull quay.io/crw/pluginregistry-rhel8:latest
reworked to pull the `2.x` tag

2022-01-24 11:03 UTC, vinokurig commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          VERSION_DIR="latest"
reworked to pull the `2.x` tag

2022-01-24 11:10 UTC, vinokurig commented
@nickboldt
> needs arch support; unclear why we include BOTH surge and gh pages. Suggest only using gh.

Added arch support, removed the `surge.sh` logic.

2022-01-24 16:34 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            version="${GITHUB_REF_NAME:4:4}"
might be safer to just read https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/VERSION = 2.16 or https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.15-rhel-8/dependencies/VERSION = 2.15

2022-01-24 16:38 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/$arch/v3/plugins/"
"checkout" implies a git checkout... do you mean..
`echo "Plugin registry published to https://..."` ?

2022-01-24 16:40 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +      - 'crw-[0-9].[0-9]+-rhel-8'
this will only fire for 2.yy branches, but not the 2.next branch, `crw-2-rhel-8`. 

Is the plan to have this only work for the stable branches, and have next builds broken until we are ready to branch?

2022-01-24 17:04 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            docker create --name pluginRegistry quay.io/crw/pluginregistry-rhel8:"$version" sh
Tried this locally and it fails when run on x64 against a ppc64le image:

```
$➔ arch=ppc64le
$➔ version=2.14
$➔ docker pull quay.io/crw/pluginregistry-rhel8:"$version" --platform="$arch"
2.14: Pulling from crw/pluginregistry-rhel8
Digest: sha256:650a715a08927b11d78d8f520d0d9b623a3f9193eb98e1aed6eeebcaf4517b15
Status: Downloaded newer image for quay.io/crw/pluginregistry-rhel8:2.14

$➔             docker create --name pluginRegistry quay.io/crw/pluginregistry-rhel8:"$version" sh
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
461e496615e1ec669d2a97433cd455cfaeb40db50e548c21faaa9e31512f5f4e
```

is the ubuntu runner multiarch or smart enough to fake it? I don't see you using buildx here...

2022-01-24 17:31 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          LATEST_VERSION_DIR="che-plugin-registry/latest"
This builds branches like `crw-2.15-rhel-8 ...`(stable)

2022-01-24 17:56 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            version="${GITHUB_REF_NAME:4:4}"
what if another branch triggered the build?

2022-01-24 18:14 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            docker create --name pluginRegistry quay.io/crw/pluginregistry-rhel8:"$version" sh
fixed by adding `platform` param to the `create` command

2022-01-24 19:24 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            docker create --name pluginRegistry quay.io/crw/pluginregistry-rhel8:"$version" sh
aha! nice.

https://vinokurig.github.io/codeready-workspaces/che-plugin-registry/crw-2.15-rhel-8/ppc64le/v3/plugins/redhat/vscode-apache-camel/latest/ shows we have reference to the correct `plugin-java11-openj9-rhel8` image, so this appears to be working :D

2022-01-24 19:26 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            version="${GITHUB_REF_NAME:4:4}"
well...
if triggered from crw-2 branch, you want to build new :2.16 / :next bits.
if triggered from crw-2.15-rhel-8 branch, you want to build new :2.15 / :latest bits.

so in either case, we get the correct source image, resulting GH page + path.

2022-01-24 19:27 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          LATEST_VERSION_DIR="che-plugin-registry/latest"
yes, and it ALSO needs to build from the `crw-2-rhel-8` branch / images (CI)

2022-01-24 19:29 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          echo "Checkout the published plugin registry at https://$GITHUB_ACTOR.github.io/$GITHUB_REPO_NAME/$VERSION_DIR/v3/plugins/"
:+1:

2022-01-24 19:31 UTC, nickboldt commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +          docker pull quay.io/crw/pluginregistry-rhel8:latest
2.x = CI / :next / future / crw-2-rhel-8.

2.yy = stable / :latest / upcoming release / crw-2.yy-rhel-8

2022-01-25 19:06 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +      - 'crw-[0-9].[0-9]+-rhel-8'
added generation of `next`

2022-01-25 19:07 UTC, vinokurig commented on .github/workflows/plugin-registry-latest-build-publish-content.yaml
> +      - crw-2-rhel-8
added generation of `next`

2022-01-25 19:07 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            version="${GITHUB_REF_NAME:4:4}"
done

2022-01-25 19:07 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          LATEST_VERSION_DIR="che-plugin-registry/latest"
done

2022-01-25 19:11 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +             version="latest"
why don't you want a 2.16 version here?

2022-01-25 19:11 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            VERSION_DIR="che-plugin-registry/next"
so... for ci/next, we publish to ONLY next, but for stable/latest we publish to BOTH 2.15 and latest. 

Do... we need difference?

2022-01-25 19:12 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          if [[ "$GITHUB_REF_NAME" != "crw-2-rhel-8" ]] && ! [[ $(git ls-remote origin crw-$(echo $VERSION + 0.01 | bc -l)-rhel-8) ]]; then
what `bc` is this? On my machine it's Beyond Compare... but I suspect you mean something else.

2022-01-25 19:16 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          if [[ "$GITHUB_REF_NAME" != "crw-2-rhel-8" ]] && ! [[ $(git ls-remote origin crw-$(echo $VERSION + 0.01 | bc -l)-rhel-8) ]]; then
are you just checking that a future stable branch exists (eg., for `GITHUB_REF_NAME` = crw-2.15-rhel-8, you appear to be testing if crw-2.16-rhel-8 is NOT a branch. 

Why?

2022-01-25 19:17 UTC, nickboldt commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          if [[ "$GITHUB_REF_NAME" != "crw-2-rhel-8" ]] && ! [[ $(git ls-remote origin crw-$(echo $VERSION + 0.01 | bc -l)-rhel-8) ]]; then
if the 2.15 branch **isn't** the latest, and this fires for a new commit in an older 2.yy branch (like 2.14)... isn't that a good thing?

2022-01-26 07:52 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +             version="latest"
Do you mean a version from `dependencies/VERSION`? For that we generate from stable branches.

2022-01-26 08:01 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +            VERSION_DIR="che-plugin-registry/next"
As far as I understand `next` is a development version and is always changing, while `stable branch / latest` is a fixed version which is not expected to change. That's why when `next` is updated we publish only it, but when `2.15` is updated it means that we need to publish the brunch and `latest` as a reference to the latest stable brunch.

2022-01-26 08:10 UTC, vinokurig commented on .github/workflows/plugin-registry-build-publish-content-gh-pages.yaml
> +          if [[ "$GITHUB_REF_NAME" != "crw-2-rhel-8" ]] && ! [[ $(git ls-remote origin crw-$(echo $VERSION + 0.01 | bc -l)-rhel-8) ]]; then
> what bc is this? On my machine it's Beyond Compare... but I suspect you mean something else.

This is [`Bash Calculator`](https://www.tutorialsandyou.com/bash-shell-scripting/bash-bc-18.html)
If just `$(( 2.15 + 0.01 ))` then it returns `2.0099999999999998`
> Are you just checking that a future stable branch exists (eg., for GITHUB_REF_NAME = crw-2.15-rhel-8, you appear to be testing if crw-2.16-rhel-8 is NOT a branch) ?
>
>Why?
>
> if the 2.15 branch isn't the latest, and this fires for a new commit in an older 2.yy branch (like 2.14)... isn't that a good thing?

This is needed to be sure that the triggered branch is latest. Otherwise we mustn't update the `latest` folder.

2022-01-28 08:19 UTC, svor approved these changes
LGTM

2022-01-28 14:13 UTC, nickboldt approved these changes

2022-01-28 14:13 UTC, merged

2022-01-28 14:38 UTC, nickboldt commented
gh-page branch set up so only the bot can publish there.

Now running https://github.com/redhat-developer/codeready-workspaces/actions/workflows/plugin-registry-build-publish-content-gh-pages.yaml for both 2.15 and 2.16 branches